/* Generated by Pyrex 0.9.5.1a on Thu Oct 25 16:44:34 2007 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "math.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static PyObject *__Pyx_UnpackItem(PyObject *); /*proto*/
static int __Pyx_EndUnpack(PyObject *); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from Ellipse */

static PyObject *__pyx_k4;


/* Implementation of Ellipse */

static char (__pyx_k1[]) = "Lib.Point";

static PyObject *__pyx_n_Point;
static PyObject *__pyx_n_Ellipse;
static PyObject *__pyx_n_object;
static PyObject *__pyx_n___init__;
static PyObject *__pyx_n___getinitargs__;
static PyObject *__pyx_n_paint;
static PyObject *__pyx_n_intersections;
static PyObject *__pyx_n_inside;

static PyObject *__pyx_k1p;

static PyObject *__pyx_n_rect;

static PyObject *__pyx_f_7Ellipse_7Ellipse___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_7Ellipse_7Ellipse___init__ = {"__init__", (PyCFunction)__pyx_f_7Ellipse_7Ellipse___init__, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_7Ellipse_7Ellipse___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_rect = 0;
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {"self","rect",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_self, &__pyx_v_rect)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_rect);

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":9 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_rect, __pyx_v_rect) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("Ellipse.Ellipse.__init__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_rect);
  return __pyx_r;
}

static PyObject *__pyx_f_7Ellipse_7Ellipse___getinitargs__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_7Ellipse_7Ellipse___getinitargs__ = {"__getinitargs__", (PyCFunction)__pyx_f_7Ellipse_7Ellipse___getinitargs__, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_7Ellipse_7Ellipse___getinitargs__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"self",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_self)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":11 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_rect); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("Ellipse.Ellipse.__getinitargs__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_pygame;
static PyObject *__pyx_n_x;
static PyObject *__pyx_n_y;
static PyObject *__pyx_n_w;
static PyObject *__pyx_n_h;
static PyObject *__pyx_n_draw;
static PyObject *__pyx_n_ellipse;


static PyObject *__pyx_f_7Ellipse_7Ellipse_paint(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_7Ellipse_7Ellipse_paint = {"paint", (PyCFunction)__pyx_f_7Ellipse_7Ellipse_paint, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_7Ellipse_7Ellipse_paint(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_offset = 0;
  PyObject *__pyx_v_surface = 0;
  PyObject *__pyx_v_fore_color = 0;
  PyObject *__pyx_v_back_color = 0;
  PyObject *__pyx_v_pygame;
  PyObject *__pyx_v_rect;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  int __pyx_6;
  static char *__pyx_argnames[] = {"self","offset","surface","fore_color","back_color",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOOO", __pyx_argnames, &__pyx_v_self, &__pyx_v_offset, &__pyx_v_surface, &__pyx_v_fore_color, &__pyx_v_back_color)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_offset);
  Py_INCREF(__pyx_v_surface);
  Py_INCREF(__pyx_v_fore_color);
  Py_INCREF(__pyx_v_back_color);
  __pyx_v_pygame = Py_None; Py_INCREF(Py_None);
  __pyx_v_rect = Py_None; Py_INCREF(Py_None);

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":14 */
  __pyx_1 = __Pyx_Import(__pyx_n_pygame, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; goto __pyx_L1;}
  Py_DECREF(__pyx_v_pygame);
  __pyx_v_pygame = __pyx_1;
  __pyx_1 = 0;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":15 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_rect); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_x); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_v_offset, __pyx_n_x); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  __pyx_3 = PyNumber_Add(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_rect); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_y); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_v_offset, __pyx_n_y); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  __pyx_4 = PyNumber_Add(__pyx_1, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_rect); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_w); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_rect); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  __pyx_5 = PyObject_GetAttr(__pyx_1, __pyx_n_h); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_3);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_4);
  PyTuple_SET_ITEM(__pyx_1, 2, __pyx_2);
  PyTuple_SET_ITEM(__pyx_1, 3, __pyx_5);
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_2 = 0;
  __pyx_5 = 0;
  Py_DECREF(__pyx_v_rect);
  __pyx_v_rect = __pyx_1;
  __pyx_1 = 0;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":16 */
  __pyx_3 = PyObject_GetAttr(__pyx_v_pygame, __pyx_n_draw); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  __pyx_4 = PyObject_GetAttr(__pyx_3, __pyx_n_ellipse); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  Py_INCREF(__pyx_v_surface);
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_surface);
  Py_INCREF(__pyx_v_back_color);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_v_back_color);
  Py_INCREF(__pyx_v_rect);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_v_rect);
  PyTuple_SET_ITEM(__pyx_5, 3, __pyx_2);
  __pyx_2 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_4, __pyx_5); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":17 */
  __pyx_3 = PyInt_FromLong(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  __pyx_2 = PyObject_GetItem(__pyx_v_rect, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_4 = PyInt_FromLong(5); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_2, __pyx_4, &__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  __pyx_6 = __pyx_6 > 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (__pyx_6) {
    __pyx_5 = PyInt_FromLong(3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
    __pyx_1 = PyObject_GetItem(__pyx_v_rect, __pyx_5); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_3 = PyInt_FromLong(5); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_1, __pyx_3, &__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
    __pyx_6 = __pyx_6 > 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
  }
  if (__pyx_6) {

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":19 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_pygame, __pyx_n_draw); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
    __pyx_4 = PyObject_GetAttr(__pyx_2, __pyx_n_ellipse); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_5 = PyInt_FromLong(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
    __pyx_1 = PyTuple_New(4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
    Py_INCREF(__pyx_v_surface);
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_surface);
    Py_INCREF(__pyx_v_fore_color);
    PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_fore_color);
    Py_INCREF(__pyx_v_rect);
    PyTuple_SET_ITEM(__pyx_1, 2, __pyx_v_rect);
    PyTuple_SET_ITEM(__pyx_1, 3, __pyx_5);
    __pyx_5 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_4, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("Ellipse.Ellipse.paint");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_pygame);
  Py_DECREF(__pyx_v_rect);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_offset);
  Py_DECREF(__pyx_v_surface);
  Py_DECREF(__pyx_v_fore_color);
  Py_DECREF(__pyx_v_back_color);
  return __pyx_r;
}

static PyObject *__pyx_n_ValueError;
static PyObject *__pyx_n_center;
static PyObject *__pyx_n_size;
static PyObject *__pyx_n_tuple;
static PyObject *__pyx_n_append;

static PyObject *__pyx_k7p;

static char (__pyx_k6[]) = "Returns the point of the intersection between the infinite\n        line defined by (src, dest) and this shape, or None if there\n        is no such intersection";
static char (__pyx_k7[]) = "Line is not defined by a single point";

static PyObject *__pyx_f_7Ellipse_7Ellipse_intersections(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_7Ellipse_7Ellipse_intersections = {"intersections", (PyCFunction)__pyx_f_7Ellipse_7Ellipse_intersections, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_7Ellipse_7Ellipse_intersections(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_src = 0;
  PyObject *__pyx_v_dest = 0;
  PyObject *__pyx_v_margin_error = 0;
  double __pyx_v_cx;
  double __pyx_v_cy;
  double __pyx_v_w;
  double __pyx_v_h;
  double __pyx_v_x1;
  double __pyx_v_y1;
  double __pyx_v_x2;
  double __pyx_v_y2;
  double __pyx_v_m;
  double __pyx_v_n;
  double __pyx_v_s;
  double __pyx_v_sq;
  double __pyx_v_div;
  double __pyx_v_xexpr;
  double __pyx_v_yexpr;
  double __pyx_v_yexpr1;
  double __pyx_v_yexpr2;
  double __pyx_v_cmargin_error;
  double __pyx_v_n_2;
  double __pyx_v_m_2;
  double __pyx_v_h_2;
  double __pyx_v_w_2;
  double __pyx_v_cx_2;
  double __pyx_v_cy_2;
  double __pyx_v_tempx;
  double __pyx_v_tempy;
  PyObject *__pyx_v_i1;
  PyObject *__pyx_v_i2;
  PyObject *__pyx_v_res;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  double __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  double __pyx_5;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  static char *__pyx_argnames[] = {"self","src","dest","margin_error",0};
  __pyx_v_margin_error = __pyx_k4;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO|O", __pyx_argnames, &__pyx_v_self, &__pyx_v_src, &__pyx_v_dest, &__pyx_v_margin_error)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_src);
  Py_INCREF(__pyx_v_dest);
  Py_INCREF(__pyx_v_margin_error);
  __pyx_v_i1 = Py_None; Py_INCREF(Py_None);
  __pyx_v_i2 = Py_None; Py_INCREF(Py_None);
  __pyx_v_res = Py_None; Py_INCREF(Py_None);
  __pyx_v_i = Py_None; Py_INCREF(Py_None);

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":30 */
  __pyx_1 = PyFloat_AsDouble(__pyx_v_margin_error); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  __pyx_v_cmargin_error = __pyx_1;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":32 */
  __pyx_k6;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":35 */
  if (PyObject_Cmp(__pyx_v_src, __pyx_v_dest, &__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
  __pyx_2 = __pyx_2 == 0;
  if (__pyx_2) {

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":36 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_ValueError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}
    __Pyx_Raise(__pyx_3, __pyx_k7p, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":37 */
  __pyx_3 = PyObject_GetAttr(__pyx_v_self, __pyx_n_rect); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  __pyx_4 = PyObject_GetAttr(__pyx_3, __pyx_n_center); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_3 = PyObject_GetIter(__pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = __Pyx_UnpackItem(__pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  __pyx_1 = PyFloat_AsDouble(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_v_cx = __pyx_1;
  __pyx_4 = __Pyx_UnpackItem(__pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  __pyx_1 = PyFloat_AsDouble(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_v_cy = __pyx_1;
  if (__Pyx_EndUnpack(__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":38 */
  __pyx_4 = PyObject_GetAttr(__pyx_v_self, __pyx_n_rect); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_4, __pyx_n_size); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = PyObject_GetIter(__pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_3 = __Pyx_UnpackItem(__pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  __pyx_1 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_v_w = __pyx_1;
  __pyx_3 = __Pyx_UnpackItem(__pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  __pyx_1 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_v_h = __pyx_1;
  if (__Pyx_EndUnpack(__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":39 */
  __pyx_3 = PyObject_GetAttr(__pyx_v_src, __pyx_n_x); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
  __pyx_1 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_4 = PyObject_GetAttr(__pyx_v_src, __pyx_n_y); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
  __pyx_5 = PyFloat_AsDouble(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_v_x1 = __pyx_1;
  __pyx_v_y1 = __pyx_5;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":40 */
  __pyx_3 = PyObject_GetAttr(__pyx_v_dest, __pyx_n_x); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  __pyx_1 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_4 = PyObject_GetAttr(__pyx_v_dest, __pyx_n_y); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  __pyx_5 = PyFloat_AsDouble(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_v_x2 = __pyx_1;
  __pyx_v_y2 = __pyx_5;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":41 */
  __pyx_2 = (__pyx_v_x1 == __pyx_v_x2);
  if (__pyx_2) {

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":43 */
    __pyx_v_m = ((1. * (__pyx_v_x2 - __pyx_v_x1)) / (__pyx_v_y2 - __pyx_v_y1));

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":44 */
    __pyx_v_n = ((1. * ((__pyx_v_x1 * __pyx_v_y2) - (__pyx_v_x2 * __pyx_v_y1))) / (__pyx_v_y2 - __pyx_v_y1));

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":46 */
    __pyx_v_n_2 = (__pyx_v_n * __pyx_v_n);

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":47 */
    __pyx_v_m_2 = (__pyx_v_m * __pyx_v_m);

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":48 */
    __pyx_v_h_2 = (__pyx_v_h * __pyx_v_h);

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":49 */
    __pyx_v_w_2 = (__pyx_v_w * __pyx_v_w);

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":50 */
    __pyx_v_cx_2 = (__pyx_v_cx * __pyx_v_cx);

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":51 */
    __pyx_v_cy_2 = (__pyx_v_cy * __pyx_v_cy);

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":53 */
    __pyx_v_s = ((((((((-4.) * __pyx_v_n_2) - (((8 * __pyx_v_cy) * __pyx_v_m) * __pyx_v_n)) + ((8 * __pyx_v_cx) * __pyx_v_n)) + ((__pyx_v_h_2 - (4 * __pyx_v_cy_2)) * __pyx_v_m_2)) + (((8 * __pyx_v_cx) * __pyx_v_cy) * __pyx_v_m)) + __pyx_v_w_2) - (4 * __pyx_v_cx_2));

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":54 */
    __pyx_2 = (__pyx_v_s < 0);
    if (__pyx_2) {

      /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":55 */
      __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_tuple); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
      __pyx_4 = PyObject_CallObject(__pyx_3, 0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_r = __pyx_4;
      __pyx_4 = 0;
      goto __pyx_L0;
      goto __pyx_L4;
    }
    __pyx_L4:;

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":56 */
    __pyx_v_sq = ((sqrt(__pyx_v_s) * __pyx_v_h) * __pyx_v_w);

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":57 */
    __pyx_v_div = (((2. * __pyx_v_h_2) * __pyx_v_m_2) + (2 * __pyx_v_w_2));

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":59 */
    __pyx_v_xexpr = ((((2. * __pyx_v_w_2) * __pyx_v_n) + (((2 * __pyx_v_cx) * __pyx_v_h_2) * __pyx_v_m_2)) + (((2 * __pyx_v_cy) * __pyx_v_w_2) * __pyx_v_m));

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":60 */
    __pyx_v_yexpr = (((((2. * __pyx_v_h_2) * __pyx_v_m) * __pyx_v_n) - (((2 * __pyx_v_cx) * __pyx_v_h_2) * __pyx_v_m)) - ((2 * __pyx_v_cy) * __pyx_v_w_2));

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":62 */
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_Point); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
    __pyx_4 = PyFloat_FromDouble(((-((__pyx_v_m * __pyx_v_sq) - __pyx_v_xexpr)) / __pyx_v_div)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
    __pyx_6 = PyFloat_FromDouble(((-(__pyx_v_sq + __pyx_v_yexpr)) / __pyx_v_div)); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
    __pyx_7 = PyTuple_New(2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_7, 0, __pyx_4);
    PyTuple_SET_ITEM(__pyx_7, 1, __pyx_6);
    __pyx_4 = 0;
    __pyx_6 = 0;
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_7);
    __pyx_7 = 0;
    __pyx_6 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_v_i1);
    __pyx_v_i1 = __pyx_6;
    __pyx_6 = 0;

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":63 */
    __pyx_7 = __Pyx_GetName(__pyx_m, __pyx_n_Point); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    __pyx_3 = PyFloat_FromDouble(((-(((-__pyx_v_m) * __pyx_v_sq) - __pyx_v_xexpr)) / __pyx_v_div)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    __pyx_4 = PyFloat_FromDouble(((-((-__pyx_v_sq) + __pyx_v_yexpr)) / __pyx_v_div)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    __pyx_6 = PyTuple_New(2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_6, 0, __pyx_3);
    PyTuple_SET_ITEM(__pyx_6, 1, __pyx_4);
    __pyx_3 = 0;
    __pyx_4 = 0;
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_6);
    __pyx_6 = 0;
    __pyx_4 = PyObject_CallObject(__pyx_7, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_v_i2);
    __pyx_v_i2 = __pyx_4;
    __pyx_4 = 0;
    goto __pyx_L3;
  }
  /*else*/ {

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":66 */
    __pyx_v_m = ((__pyx_v_y2 - __pyx_v_y1) / (__pyx_v_x2 - __pyx_v_x1));

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":67 */
    __pyx_v_n = (((__pyx_v_x2 * __pyx_v_y1) - (__pyx_v_x1 * __pyx_v_y2)) / (__pyx_v_x2 - __pyx_v_x1));

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":69 */
    __pyx_v_n_2 = (__pyx_v_n * __pyx_v_n);

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":70 */
    __pyx_v_m_2 = (__pyx_v_m * __pyx_v_m);

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":71 */
    __pyx_v_h_2 = (__pyx_v_h * __pyx_v_h);

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":72 */
    __pyx_v_w_2 = (__pyx_v_w * __pyx_v_w);

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":73 */
    __pyx_v_cx_2 = (__pyx_v_cx * __pyx_v_cx);

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":74 */
    __pyx_v_cy_2 = (__pyx_v_cy * __pyx_v_cy);

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":76 */
    __pyx_v_s = (((((((((-4) * __pyx_v_n_2) - (((8 * __pyx_v_cx) * __pyx_v_m) * __pyx_v_n)) + ((8 * __pyx_v_cy) * __pyx_v_n)) + (__pyx_v_w_2 * __pyx_v_m_2)) - ((4 * __pyx_v_cx_2) * __pyx_v_m_2)) + (((8 * __pyx_v_cx) * __pyx_v_cy) * __pyx_v_m)) + __pyx_v_h_2) - (4 * __pyx_v_cy_2));

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":77 */
    __pyx_2 = (__pyx_v_s < 0);
    if (__pyx_2) {

      /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":78 */
      __pyx_6 = __Pyx_GetName(__pyx_b, __pyx_n_tuple); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
      __pyx_7 = PyObject_CallObject(__pyx_6, 0); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      __pyx_r = __pyx_7;
      __pyx_7 = 0;
      goto __pyx_L0;
      goto __pyx_L5;
    }
    __pyx_L5:;

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":79 */
    __pyx_v_sq = ((sqrt(__pyx_v_s) * __pyx_v_h) * __pyx_v_w);

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":80 */
    __pyx_v_div = (((2. * __pyx_v_w_2) * __pyx_v_m_2) + (2 * __pyx_v_h_2));

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":81 */
    __pyx_v_xexpr = (((((2. * __pyx_v_w_2) * __pyx_v_m) * __pyx_v_n) - (((2 * __pyx_v_cy) * __pyx_v_w_2) * __pyx_v_m)) - ((2 * __pyx_v_cx) * __pyx_v_h_2));

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":82 */
    __pyx_v_yexpr1 = ((2. * __pyx_v_cx) * __pyx_v_h_2);

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":83 */
    __pyx_v_yexpr2 = (((2. * __pyx_v_h_2) * __pyx_v_n) + (((2 * __pyx_v_cy) * __pyx_v_w_2) * __pyx_v_m_2));

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":84 */
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_Point); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
    __pyx_4 = PyFloat_FromDouble(((-(__pyx_v_sq + __pyx_v_xexpr)) / __pyx_v_div)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
    __pyx_6 = PyFloat_FromDouble((((__pyx_v_m * (__pyx_v_yexpr1 - __pyx_v_sq)) + __pyx_v_yexpr2) / __pyx_v_div)); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
    __pyx_7 = PyTuple_New(2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_7, 0, __pyx_4);
    PyTuple_SET_ITEM(__pyx_7, 1, __pyx_6);
    __pyx_4 = 0;
    __pyx_6 = 0;
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_7);
    __pyx_7 = 0;
    __pyx_6 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_v_i1);
    __pyx_v_i1 = __pyx_6;
    __pyx_6 = 0;

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":85 */
    __pyx_7 = __Pyx_GetName(__pyx_m, __pyx_n_Point); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
    __pyx_3 = PyFloat_FromDouble(((-((-__pyx_v_sq) + __pyx_v_xexpr)) / __pyx_v_div)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
    __pyx_4 = PyFloat_FromDouble((((__pyx_v_m * (__pyx_v_yexpr1 + __pyx_v_sq)) + __pyx_v_yexpr2) / __pyx_v_div)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
    __pyx_6 = PyTuple_New(2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_6, 0, __pyx_3);
    PyTuple_SET_ITEM(__pyx_6, 1, __pyx_4);
    __pyx_3 = 0;
    __pyx_4 = 0;
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_6);
    __pyx_6 = 0;
    __pyx_4 = PyObject_CallObject(__pyx_7, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_v_i2);
    __pyx_v_i2 = __pyx_4;
    __pyx_4 = 0;
  }
  __pyx_L3:;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":87 */
  __pyx_6 = PyList_New(0); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  Py_DECREF(__pyx_v_res);
  __pyx_v_res = __pyx_6;
  __pyx_6 = 0;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":88 */
  __pyx_7 = PyList_New(2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  Py_INCREF(__pyx_v_i1);
  PyList_SET_ITEM(__pyx_7, 0, __pyx_v_i1);
  Py_INCREF(__pyx_v_i2);
  PyList_SET_ITEM(__pyx_7, 1, __pyx_v_i2);
  __pyx_3 = PyObject_GetIter(__pyx_7); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  for (;;) {
    __pyx_4 = PyIter_Next(__pyx_3);
    if (!__pyx_4) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_4;
    __pyx_4 = 0;

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":89 */
    __pyx_6 = PyObject_GetAttr(__pyx_v_i, __pyx_n_x); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
    __pyx_1 = PyFloat_AsDouble(__pyx_6); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_v_tempx = __pyx_1;

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":90 */
    __pyx_7 = PyObject_GetAttr(__pyx_v_i, __pyx_n_y); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    __pyx_5 = PyFloat_AsDouble(__pyx_7); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_v_tempy = __pyx_5;

    /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":91 */
    __pyx_2 = (__pyx_v_x1 - __pyx_v_cmargin_error) <= __pyx_v_tempx;
    if (__pyx_2) {
      __pyx_2 = __pyx_v_tempx <= (__pyx_v_x2 + __pyx_v_cmargin_error);
    }
    if (!__pyx_2) {
      __pyx_2 = (__pyx_v_x2 - __pyx_v_cmargin_error) <= __pyx_v_tempx;
      if (__pyx_2) {
        __pyx_2 = __pyx_v_tempx <= (__pyx_v_x1 + __pyx_v_cmargin_error);
      }
    }
    if (__pyx_2) {
      __pyx_2 = (__pyx_v_y1 - __pyx_v_cmargin_error) <= __pyx_v_tempy;
      if (__pyx_2) {
        __pyx_2 = __pyx_v_tempy <= (__pyx_v_y2 + __pyx_v_cmargin_error);
      }
    }
    if (!__pyx_2) {
      __pyx_2 = (__pyx_v_y2 - __pyx_v_cmargin_error) <= __pyx_v_tempy;
      if (__pyx_2) {
        __pyx_2 = __pyx_v_tempy <= (__pyx_v_y1 + __pyx_v_cmargin_error);
      }
    }
    if (__pyx_2) {

      /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":95 */
      __pyx_4 = PyObject_GetAttr(__pyx_v_res, __pyx_n_append); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
      __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
      Py_INCREF(__pyx_v_i);
      PyTuple_SET_ITEM(__pyx_6, 0, __pyx_v_i);
      __pyx_7 = PyObject_CallObject(__pyx_4, __pyx_6); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      goto __pyx_L8;
    }
    __pyx_L8:;
  }
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":96 */
  __pyx_4 = __Pyx_GetName(__pyx_b, __pyx_n_tuple); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  Py_INCREF(__pyx_v_res);
  PyTuple_SET_ITEM(__pyx_6, 0, __pyx_v_res);
  __pyx_7 = PyObject_CallObject(__pyx_4, __pyx_6); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  __pyx_r = __pyx_7;
  __pyx_7 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("Ellipse.Ellipse.intersections");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_i1);
  Py_DECREF(__pyx_v_i2);
  Py_DECREF(__pyx_v_res);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_src);
  Py_DECREF(__pyx_v_dest);
  Py_DECREF(__pyx_v_margin_error);
  return __pyx_r;
}

static PyObject *__pyx_n_width;
static PyObject *__pyx_n_height;

static PyObject *__pyx_f_7Ellipse_7Ellipse_inside(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_7Ellipse_7Ellipse_inside = {"inside", (PyCFunction)__pyx_f_7Ellipse_7Ellipse_inside, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_7Ellipse_7Ellipse_inside(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_p = 0;
  PyObject *__pyx_v_cx;
  PyObject *__pyx_v_cy;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  static char *__pyx_argnames[] = {"self","p",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_self, &__pyx_v_p)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_p);
  __pyx_v_cx = Py_None; Py_INCREF(Py_None);
  __pyx_v_cy = Py_None; Py_INCREF(Py_None);

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":100 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_rect); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_center); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetIter(__pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  Py_DECREF(__pyx_v_cx);
  __pyx_v_cx = __pyx_2;
  __pyx_2 = 0;
  __pyx_2 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  Py_DECREF(__pyx_v_cy);
  __pyx_v_cy = __pyx_2;
  __pyx_2 = 0;
  if (__Pyx_EndUnpack(__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":101 */
  __pyx_2 = PyFloat_FromDouble(2.); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_1 = PyObject_GetAttr(__pyx_v_p, __pyx_n_x); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_3 = PyNumber_Subtract(__pyx_1, __pyx_v_cx); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyNumber_Multiply(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_rect); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_width); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyNumber_Divide(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_1 = PyInt_FromLong(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_3 = PyNumber_Power(__pyx_2, __pyx_1, Py_None); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_2 = PyFloat_FromDouble(2.); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_1 = PyObject_GetAttr(__pyx_v_p, __pyx_n_y); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_4 = PyNumber_Subtract(__pyx_1, __pyx_v_cy); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyNumber_Multiply(__pyx_2, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_rect); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_4 = PyObject_GetAttr(__pyx_2, __pyx_n_height); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyNumber_Divide(__pyx_1, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_1 = PyInt_FromLong(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_4 = PyNumber_Power(__pyx_2, __pyx_1, Py_None); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_2 = PyNumber_Add(__pyx_3, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_2, __pyx_1, &__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_5 = __pyx_5 <= 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_3 = PyInt_FromLong(__pyx_5); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("Ellipse.Ellipse.inside");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_cx);
  Py_DECREF(__pyx_v_cy);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_p);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_Ellipse, "Ellipse"},
  {&__pyx_n_Point, "Point"},
  {&__pyx_n_ValueError, "ValueError"},
  {&__pyx_n___getinitargs__, "__getinitargs__"},
  {&__pyx_n___init__, "__init__"},
  {&__pyx_n_append, "append"},
  {&__pyx_n_center, "center"},
  {&__pyx_n_draw, "draw"},
  {&__pyx_n_ellipse, "ellipse"},
  {&__pyx_n_h, "h"},
  {&__pyx_n_height, "height"},
  {&__pyx_n_inside, "inside"},
  {&__pyx_n_intersections, "intersections"},
  {&__pyx_n_object, "object"},
  {&__pyx_n_paint, "paint"},
  {&__pyx_n_pygame, "pygame"},
  {&__pyx_n_rect, "rect"},
  {&__pyx_n_size, "size"},
  {&__pyx_n_tuple, "tuple"},
  {&__pyx_n_w, "w"},
  {&__pyx_n_width, "width"},
  {&__pyx_n_x, "x"},
  {&__pyx_n_y, "y"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k1p, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_k7p, __pyx_k7, sizeof(__pyx_k7)},
  {0, 0, 0}
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initEllipse(void); /*proto*/
PyMODINIT_FUNC initEllipse(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("Ellipse", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":1 */
  __pyx_1 = PyList_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_INCREF(__pyx_n_Point);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_Point);
  __pyx_2 = __Pyx_Import(__pyx_k1p, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_Point); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_Point, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":7 */
  __pyx_2 = PyDict_New(); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_object); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = __Pyx_CreateClass(__pyx_3, __pyx_2, __pyx_n_Ellipse, "Ellipse"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":8 */
  __pyx_3 = PyCFunction_New(&__pyx_mdef_7Ellipse_7Ellipse___init__, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_3, 0, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_SetAttr(__pyx_1, __pyx_n___init__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":10 */
  __pyx_3 = PyCFunction_New(&__pyx_mdef_7Ellipse_7Ellipse___getinitargs__, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_3, 0, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_SetAttr(__pyx_1, __pyx_n___getinitargs__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":13 */
  __pyx_3 = PyCFunction_New(&__pyx_mdef_7Ellipse_7Ellipse_paint, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_3, 0, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_SetAttr(__pyx_1, __pyx_n_paint, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":22 */
  __pyx_3 = PyFloat_FromDouble(0.0001); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  __pyx_k4 = __pyx_3;
  __pyx_3 = 0;
  __pyx_4 = PyCFunction_New(&__pyx_mdef_7Ellipse_7Ellipse_intersections, 0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  __pyx_5 = PyMethod_New(__pyx_4, 0, __pyx_1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_1, __pyx_n_intersections, __pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;

  /* "/home/noam/enough/trunk/graphui/Shapes/Ellipse.pyx":99 */
  __pyx_4 = PyCFunction_New(&__pyx_mdef_7Ellipse_7Ellipse_inside, 0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  __pyx_5 = PyMethod_New(__pyx_4, 0, __pyx_1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_1, __pyx_n_inside, __pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_Ellipse, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("Ellipse");
}

static char *__pyx_filenames[] = {
  "Ellipse.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type)) {
        if (PyErr_Warn(PyExc_DeprecationWarning,
                "raising a string exception is deprecated"))
            goto raise_error;
    }
    else if (PyType_Check(type) || PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        if (PyInstance_Check(type))
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
        else
            type = (PyObject*) type->ob_type;
        Py_INCREF(type);
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static void __Pyx_UnpackError(void) {
    PyErr_SetString(PyExc_ValueError, "unpack sequence of wrong size");
}

static PyObject *__Pyx_UnpackItem(PyObject *iter) {
    PyObject *item;
    if (!(item = PyIter_Next(iter))) {
        if (!PyErr_Occurred())
            __Pyx_UnpackError();
    }
    return item;
}

static int __Pyx_EndUnpack(PyObject *iter) {
    PyObject *item;
    if ((item = PyIter_Next(iter))) {
        Py_DECREF(item);
        __Pyx_UnpackError();
        return -1;
    }
    else if (!PyErr_Occurred())
        return 0;
    else
        return -1;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
